imports:
    - { resource: tables.yml }

services:
    stevotvr.flair.entity.category:
        class: stevotvr\flair\entity\category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.flair.tables.cats%'
    stevotvr.flair.entity.flair:
        class: stevotvr\flair\entity\flair
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
    stevotvr.flair.operator.category:
        class: stevotvr\flair\operator\category
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.cats%'
            - '%stevotvr.flair.tables.flair%'
    stevotvr.flair.operator.flair:
        class: stevotvr\flair\operator\flair
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
