imports:
    - { resource: tables.yml }

services:
    stevotvr.flair.listener:
        class: stevotvr\flair\event\main_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@stevotvr.flair.operator.user'
        tags:
            - { name: event.listener }
    stevotvr.flair.controller.acp.main:
        class: stevotvr\flair\controller\acp_main_controller
        arguments:
            - '@stevotvr.flair.operator.category'
            - '@service_container'
            - '@stevotvr.flair.operator.flair'
            - '@language'
            - '@request'
            - '@template'
    stevotvr.flair.controller.acp.user:
        class: stevotvr\flair\controller\acp_user_controller
        arguments:
            - '@stevotvr.flair.operator.category'
            - '@config'
            - '@dbal.conn'
            - '@stevotvr.flair.operator.flair'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@stevotvr.flair.operator.user'
            - '%core.root_path%'
            - '%core.php_ext%'
    stevotvr.flair.controller.legend:
        class: stevotvr\flair\controller\legend_controller
        arguments:
            - '@stevotvr.flair.operator.category'
            - '@stevotvr.flair.operator.flair'
            - '@controller.helper'
            - '@language'
            - '@template'
    stevotvr.flair.entity.flair:
        class: stevotvr\flair\entity\flair
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
    stevotvr.flair.entity.category:
        class: stevotvr\flair\entity\category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair_categories%'
    stevotvr.flair.operator.flair:
        class: stevotvr\flair\operator\flair
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
            - '%stevotvr.flair.tables.flair_categories%'
            - '%stevotvr.flair.tables.flair_users%'
    stevotvr.flair.operator.category:
        class: stevotvr\flair\operator\category
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
            - '%stevotvr.flair.tables.flair_categories%'
            - '%stevotvr.flair.tables.flair_users%'
    stevotvr.flair.operator.user:
        class: stevotvr\flair\operator\user
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
            - '%stevotvr.flair.tables.flair_categories%'
            - '%stevotvr.flair.tables.flair_users%'
