imports:
    - { resource: tables.yml }

services:
    stevotvr.flair.entity:
        class: stevotvr\flair\entity\flair
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
    stevotvr.flair.operator:
        class: stevotvr\flair\operator\flair
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
